[package]
name = "coral"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "coral"
path = "src/main.rs"

[[bin]]
name = "coral-llvm"
path = "src/main_llvm_demo.rs"

[lib]
name = "coral"
path = "src/lib.rs"

[dependencies]
